excluded:
 Pods
disabled_rules:
 - colon
 - cyclomatic_complexity
 - file_length
 - function_body_length
 - line_length
 - opening_brace
 - statement_position
 - switch_case_alignment
 - trailing_whitespace
 - vertical_parameter_alignment
identifier_name:
 allowed_symbols: "_"
 min_length:
  warning: 0
  error: 0
 max_length:
  warning: 60
  error: 100
